### ISSUE TITLE
Sort fields in grip()

### ISSUE THREAD

**Issue by kaysap** [uweku/Vise_for_ABAP#2]
Please check the logic for sorting in ZCL_VISE=>grip()!
I changed this to 
![2016-06-22 16_23_54-class builder_ klasse zcl_vise anzeigen](https://cloud.githubusercontent.com/assets/11522893/16270204/cf84d692-3895-11e6-8f34-f88c9d3822e4.png)

**Comment by uweku** [comment]
commit c44398de72b0095a21c64ce8e9476720536a47b8 closes #2
